### ISSUE TITLE
Doesn't validate resourceTypes

### ISSUE THREAD

**Issue by wilsongp** [wilsongp/parse-raml#8]
### Should throw parsing error after fix
_undefinedType is, well, undefined as a resourceType_
```
resourceTypes:
  collection:
    put: ...
/testRoute:
  type: undefinedType
```

### Should parse correctly after fix
_should be fine since collection has been defined as a resourceType_
```
resourceTypes:
  collection:
    put: ...
/testRoute:
  type: collection
```
